### PR TITLE
Add initial features

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by eduardolundgren** [comment]
@julien Thanks for the contribution. Could you give an example of how to use this generator as well as the output ir generates and so on. I need that clarity in order to review it properly.

**Comment by julien** [comment]
@eduardolundgren you're welcome. I'll do my best to explain.

The idea, would be to generate **Web Component** definitions/files for Metal components.

I looked at other tools used in [metal-cli](https://github.com/metal/metal-cli) such as [metal-tools-build-globals](https://github.com/metal/metal-tools-build-globals) and [metal-tools-build-soy](https://github.com/metal/metal-tools-soy) and tried to use the same directory structure and conventions.

The example usage would be something like this

```javascript

var metalToolsBuildWebComponents = require('metal-tools-build-webcomponents');

metalToolsBuildWebComponents({
  src: 'src/*.js',
  dest: 'dist'
});

```

Although this works, my idea was also to "integrate" this in [metal-cli](https://github.com/metal/metal-cli) and [gulp-metal](https://github.com/metal/gulp-metal), to be able to do 

(with **metal-cli**)

```bash
metal webcomponents -s src/*.js  -d build
```

(with **gulp-metal**)
```javascript
var metal = require('gulp-metal');
metal.registerTasks({
  buildDest: 'build',
  buildSrc: 'src/*.js'
});

// This would let you run a "gulp webcomponents" task
```
 
(I actually have a fork of both with a `webcomponents` branch that contains this "change").

So given the code above, if you had a `Button.js` file in the `src` directory with the following content

```javascript
'use strict';

import {core} from 'metal';
import Component from 'metal-component';

class Button extends Component {
  attached() {}
  created() {}
}

Button.STATE = {
  disabled: {
    value: false,
    validator: core.isBoolean
  }
};

export default Button;
```

The generated output would be a file named `button-element.html` (written to the `build` directory) with the following contents:

```html
<template id="button-element-template">

</template>

<script>
(function () {
  class ButtonElement extends HTMLElement {
    constructor() {
      super();

      let shadowRoot = this.attachShadow({mode: 'open'});

      if (!document.currentScript) {
        return;
      }

      const doc = document.currentScript.ownerDocument;
      if (doc) {
        const tpl = doc.querySelector('button-element-template');
        if (tpl && tpl.content) {
	  const instance = tpl.content.cloneNode(true);
	  shadowRoot.appendChild(instance);
        }
      }

      const stateKeys = Object.keys(metal.State.getStateStatic(metal.Button));
      let opts = {};
      for (let i = 0, l = stateKeys.length; i < l; i++) {
        opts[stateKeys[i]] = this.getAttribute(stateKeys[i]);
      }
      this.observedAttrs = stateKeys;

      this.component = new metal.Button(opts, shadowRoot);
      this.component.on('*', this.emit.bind(this));
    }

    static get observedAttributes() {
      return this.observerdAttrs;
    }

    emit(...data) {
      let originalEvt = data.pop();
      const evt = new CustomEvent(originalEvt.type, {detail: data});
      this.dispatchEvent(evt);
    }

    attributeChangedCallback(attrName, oldVal, newVal) {
      this.component[attrName] = newVal;
    }
  }
  window.customElements.define('metal-button', ButtonElement);
}());
</script>
``` 

Which could then be used as a webcomponent. 

That's a lot of information, so let me know if anything is not clear.

Thanks

**Comment by eduardolundgren** [comment]
Thanks for the explanation.

Since the component view is all compiled to JavaScript can we just register the element as a web component with the portion you described without having the `.html`? That way the user can just use without the hassle of having to include on the page.

**Comment by julien** [comment]
@eduardolundgren thanks for the feedback, I think we can and seems like a cleaner approach. 
I'll have a look into this and let you know.

**Comment by eduardolundgren** [comment]
One of the goals would be to make it easier to use like this:

```soy
{template. render}
	<metal-button title="hi">
		content
	</metal-button>
{/template}
```

````jsx
render() {
	return (<metal-button title="hi">
		content
	</metal-button>);
}
```

**Comment by julien** [comment]
Yes, it makes sense.

Another thing I was thinking while reading your previous comment, since Metal components generally create their "children", it doesn't really make sense to use an `html` file to add more elements since the Metal component takes care of this.

I made the change to generate `js` files instead of `html` and they load fine in the browser as long as `metal` is loaded too.

**Comment by eduardolundgren** [comment]
Could you deploy a demo with this running so then we can inspect the code? You can deploy to WeDeploy.

**Comment by julien** [comment]
Yes, sounds like a good idea.

**Comment by julien** [comment]
@eduardolundgren, sorry I'm going a bit too fast  :)

We probably need to transpile the generated code for the demos to work in all browsers and apparently custom elements should be defined via classes (i.e. ES6) but it's not very clear if that's the only way you should do it since the [spec]((https://w3c.github.io/webcomponents/spec/custom/)) being defined.

There's a way to get it working with ES5, as you can see in [this thead](https://github.com/w3c/webcomponents/issues/587), but that doesn't really seem like the way to go either.

**Comment by julien** [comment]
Hi again @eduardolundgren,

For the moment I think it's safer to generate the `.html` file, or I need to spend a bit more time thinking this to make sure it works as it should.

Web components are mostly "imported" with a `<link rel="import" >` rather than a `<script>` tag and it also seems to behave differently (Polymer uses the 1st approach, but Skate.js seems to use something that "looks like" the second approach, this is still very "green")

- When declaring the component in an `.html` file and importing it in our "main" document (via html imports),  the web component's content is always placed inside the "imported" `.html` node (as part of it's children)
Which looks more or less like this:

```
   main html document
   -- imported webcomponent html
       -- web component "content" (metal component)
```

or

```html
<html>
  <head>
      <link ref="import" href="some-component.html">
   </head>
  <body>
    ...
   <some-component title="foo">
      <!-- some component's children are placed here -->
      <button></button>
   </some-component>
   ... 
   </body>
</html>
``` 

- When declaring the component in a `.js` file and importing it in our "main" document (via `<script>` tags),  the web component 's content is always placed in the "main" `.html` node.
Which looks more or less like this:

```
   main html document
   -- imported webcomponent html (<metal-component attr1="foo"></metal-component>)
   -- web component "content" (metal component)
``` 

or 

```html
<html>
  <head>
      <script src="some-metal-component-that-renders-web-component.js"></script>
   </head>
  <body>
    ...
   <script>
     new metal.SomeComponentThatRendersWebComponent();
   </script>

   <!-- once the metal component is attached and rendered -->
   <some-component title="foo">
      
   </some-component>

    <!-- my component's children are placed here  and not inside the "some-component" node -->
    <button></button>
   </body>
</html>
``` 

Generating `js` files is not an issue, but using them without their own "html" file and "html imports" doesn't work the same way. 

I'll get back to you with more details and changes soon, and hopefully a working demo.

Thanks

**Comment by julien** [comment]
I finally put up a demo at http://hosting.webcomponents.wedeploy.io/

The code can be found [here](https://github.com/julien/metal-demos-webcomponents) and it's pretty basic.

Let me make sure everything is up to date and I will notify you.

**Comment by julien** [comment]
I'm closing this pull request, since I opened [this](https://github.com/metal/metal.js/pull/217) one,

Thanks again for the feedback

**Pull request closed without merging**
